services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    working_dir: /app
    command: npm start
    environment:
      AWS_ACCESS_KEY_ID: "ASIA5DYSEEJ4UKKIM7IB"
      AWS_SECRET_ACCESS_KEY: "/030Z0NmTsXQYwSpkjgAxieRECfzykOZyg16tW2W"
      AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEMf//////////wEaDmFwLXNvdXRoZWFzdC0yIkgwRgIhAP79qASxwrcOe9+GZ3okssYfFk6tLQyUABBppPZ5ZYUzAiEA7C3/NjmFZ2YBCgTbK6ldRuEQFNINGAXsb6h3doD2aOoqpQMIEBADGgw5MDE0NDQyODA5NTMiDEg5LzZXU6n68SbDRSqCA1qZREZtr/DRxUufo/tMd7JEfRyVSp/ktaoUQmS2JIKqyrhXS47dR84x+oeF9ribgmidMHSu1qUN1vjsE+Ft5efpNjv8Aj3pI/kI/F7oJUWs5AEPVxb55jV60VHAe+nae4m5qY+LTlzmqyeVmLKvQUfvO2JoG5gkoSNkbZXK3ww7PEAQP4DbRugJe4i7bo/V/U4fG78PHAcRJqpXL9SqjSFq4wdZDCCLjOu9Vf/FQ3i93rZaNSw+0Pv/eQUUk9T1itakLws/dBD2p0/Ak8mMZp3VsaPWgbGnhnmvSZ3B0M+0nnCBzLxBcMqQMRNkrcTqjsd2dmTIrhVSHP9yoPKLcYsBtqTGijAykEVfVNt8QOZLgymdOGyJbLReMpUb6P7Gt2xThcT0ZKAnX0SABeHny0YpSoIubg1Q5k6OSVxjIDYo9kiOOgV/3ZQstkeZr9b+N7MKTnv6/ADBd3SA2Onwy6Qdyf8oyn0Wl4qbjESWm5Lr780xRukcQaWSF8PAvksu+nySMPyU1LcGOqUBVWINL9BEyS5H0VnlsftLiJ0/Hu4e62d2P+u9o3sA0lTqJfko7REnyR0eI5WohI7IbjUvo0VjfSji1dsNVp4rPWkqUiB3OQJnDpXVYs/CibRd0sd+uygVvZqOTjAf2JlzLgYQwZvF4N/QIlNlq5zgN1MW46h9NVui+2kXHSy4uBDfCS9TMRvE0IPi2ZK49vSvGt3uviei4QvaYRL+oXfnxyHqTvJD"
      TZ: "Australia/Brisbane"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"  
    working_dir: /app  
    command: npm start 

