services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3001:3001"  
    working_dir: /app  
    command: npm start
  
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"  
    working_dir: /app  
    command: npm start 

volumes:
  mysql-db: